#!/bin/bash
set -e

APACHE_SHIB_APACHE_MODULES_TO_START=${APACHE_SHIB_APACHE_MODULES_TO_START:-"shib2 ssl"}
APACHE_SHIB_APACHE_START_SHIB=${APACHE_SHIB_APACHE_START_SHIB:-"true"}

if [ "$APACHE_SHIB_APACHE_START_SHIB" = "true" ]; then
  /etc/init.d/shibd start
fi

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

a2enmod $APACHE_SHIB_APACHE_MODULES_TO_START

exec apachectl -DFOREGROUND
